name: Test
on:
  push:

jobs:
  build:
    name: Test - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
    steps:
      - name: Test
        shell: bash
        run: |
          apt-get install libssl-dev
