name: Test
on:
  push:

jobs:
  build:
    name: Test - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
    steps:
      - name: Test
        shell: bash
        run: |
          sudo apt update

          sudo apt-get install libssl-dev
          #sudo apt install libssh2-1


          #sudo apt-get install python3
          #sudo apt install build-essential


          #sudo apt install clang-18
          #sudo apt-get install clang-tools-18
          #sudo apt install libstdc++-12-dev
          #sudo apt install libstdc++6

          #sudo apt-get install patchelf
          #sudo apt-get -qq install -y libwayland-dev libxrandr-dev
          #sudo apt-get install libxcb-keysyms1-dev
          #sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          #sudo apt install xorg-dev
          #sudo apt install git-lfs
          #sudo apt-get install subversion
          #sudo apt-get install meson
          #sudo apt-get install cmake
          #sudo apt-get install curl zip unzip tar
          #sudo apt-get install pkg-config libfreetype-dev
          #sudo apt-get install ninja-build
